### ISSUE TITLE
Set minimum allowed TxPower

### ISSUE THREAD

**Issue by x0y1z2** [brocaar/loraserver#293]
In Service Profile I can set minimum and maximum allowed data-rate. But in some cases server set too low power by ADR to device, and if noise level increases, gateway can't receive data. I want limit minimum TxPower for solving this problem.

And I think, that it will be useful, if minimum and maximum data-rate and minimum TxPower settings will be in Device Profile.

**Comment by brocaar** [comment]
The service-profile fields are defined by the LoRaWAN Backend Interfaces specification. The min / max data-rate options are not there to make sure that the device stays connected, but to allow a network-operator to put a constraint on the used data-rates by that user. Note that the data-rate is related to the used airtime, the tx power not.

The solution in your case is to increase the installation margin:
https://docs.loraserver.io/loraserver/install/config/

```toml
  # LoRaWAN network related settings.
  [network_server.network_settings]
  # Installation margin (dB) used by the ADR engine.
  #
  # A higher number means that the network-server will keep more margin,
  # resulting in a lower data-rate but decreasing the chance that the
  # device gets disconnected because it is unable to reach one of the
  # surrounded gateways.
  installation_margin=10
```
